### ISSUE TITLE
Copy method in Field class

### ISSUE THREAD

**Issue by mb1a15** [joommf/discretisedfield#14]
Should `Field` class be able to set its value with another field like:

```
f1 = Field(mesh, dim=3, value=(0, 0, 1))
f2 = Field(mesh, dim=3)

f2.value = f1
```

Or `f2.value = f1.value` is already sufficient?

**Comment by mb1a15** [comment]
Any thoughts?

**Comment by fangohr** [comment]
If we can already do `f2.value = f1.value`, then f2 = f1 should be (!) easy.

On the other hand: have we got a use case for this? If not, maybe delay (think 'lean'), and close this for now. Let's talk this afternoon.

**Comment by mb1a15** [comment]
The idea of setting field with another field is to somehow have a "copy constructor". This is because in OOMMFC we change the magnetisation in place. What if we want to have both magnetisation before and after the driver.

Probably a better solution would be to implement `field.copy()` method, similar to the Python dictionary.

**Comment by fangohr** [comment]
Agreed.

How about overloading the `f1=f2` operator, and if it is used we provide some help, explaining the two options:

1. `f2 = f1.copy()`, which copies the `f1` object, so we have two identical objects after the operation, or

2. `f2.value = f1.value` which makes `f2.value` reference the same object as `f1.value` (i.e. not a copy of data, but just pointing to the same piece of memory; potentially losing what `f2.value` was pointing to before.)

**Comment by mb1a15** [comment]
Overloading assignment operator is not possible in Python, so `field.copy()` would be an alternative. Because we have not seen the necessity of copy constructor yet, I'm closing this issue for now, and reopen it if necessary.
