### ISSUE TITLE
Change interface for plot_slice

### ISSUE THREAD

**Issue by mb1a15** [joommf/discretisedfield#23]
The `plot_slice` function call should be, for instance,
```
plot_slice(z=50e-9)
```
or
```
plot_slice(x=20e-9)
```

**Comment by fangohr** [comment]
Another idea. We could also allow the function to be called like
<pre>
plot_slice('x')
</pre>
In that case the slice level (`point` at the moment) is missing. But we could use the average position in that direction. This would be useful for quick visualisations, in particular for flat systems where there is only one level of cubes.

We could add a printed output saying : `slice at x=2.5nm`, or even `output from plot_slice(x=2.5e-9)`.

**Comment by fangohr** [comment]
Yet another idea: `plot_slice()` could result in plotting three slices under each other, for all three directions, each printing there command. This could provide a quick overview.
