### ISSUE TITLE
Use norm_array instead of norm_value

### ISSUE THREAD

**Issue by mb1a15** [joommf/discretisedfield#26]
At the moment, we have `field.norm_value` to get the representation of the field norm and `field.norm` to get a numpy array. In order to be consistent with value, these methods should be `field.norm` and `field.norm_array`.

**Comment by fangohr** [comment]
Not wanting to override this, but just to record that a different model is used (for example by FEniCS) where `vector()` returns a FEniCS specific vector object, and `vector().array()` returns a numpy object . A similar approach is used in pandas, where there is a method `as_matrix()` (http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.as_matrix.html#) which returns a numpy array. (So really it should be called `as_array()`).

**Comment by mb1a15** [comment]
My initial idea was to have `field.norm.value` and `field.norm.array. This would mean that a Field class should contain an instance of itself (scalar Field) which could complicate a lot. I will try to make this work now.
