### ISSUE TITLE
Rename reading and writing functions

### ISSUE THREAD

**Issue by mb1a15** [joommf/discretisedfield#27]
This name is too long with too many underscores. Probably this should be just `df.read(filename.omf)`. Similarly, `field.write_oommf_file(filename.omf)` can be renamed to simple `field.write(filename.omf)`. Because we also support writing VTK files, `write` method will decide what to call by checking the filename extension.

Other options can be `fromfile()` and `tofile()`.

Any thoughts?

**Comment by fangohr** [comment]
Sounds good to me. I like `read` and `write`. I also like (a little bit less) `fromfile` and `tofile`.

**Comment by mb1a15** [comment]
Reading function is now `discretisedfield.read(filename)`. Writing still needs to be refactored.
