### ISSUE TITLE
Divide field plane plotting into steps

### ISSUE THREAD

**Issue by mb1a15** [joommf/discretisedfield#31]
There is a default `plot_plane` method which plots the plane. To allow the user to change the plot he wants, this should be broken into multiple steps that the user can call individually (`imshow`, `quiver`, `colorbar`, `hsv`).

**Comment by mb1a15** [comment]
Completed dividing plotting into `imshow` and `quiver`. Colorbar remains.

**Comment by fangohr** [comment]
Great. Could you add a notebook that demonstrates how these can be used individually, and also how the `ax=ax` parameter works?

**Comment by mb1a15** [comment]
Plotting is now divided in `imshow`, `quiver`, and `colorbar`. The temporary documentation is in `new_interface.ipynb` and will be moved when the pip package is updated.
