### ISSUE TITLE
Make divergent colormap the default one?

### ISSUE THREAD

**Issue by marijanbeg** [joommf/discretisedfield#32]
`viridis` is the default colormap. For magnetisation (out-of-plane component), divergent colormap might be better.

**Comment by mb1a15** [comment]
The best options would be `coolwarm`, `bwr`, and `seismic` colormaps. However, these colormaps become very misleading if the range of data is not full [-1, 1] which is most often the case in micromagnetics.

**Comment by fangohr** [comment]
Can we have an example of using different (user specified?) colormaps in the notebook documentation? As long as people know how to use the colormaps, they can then do what they like and deviate from the default.

**Comment by marijanbeg** [comment]
For simplicity, I would prefer not to have the magnetisation range fixed. After some testing, this opens a lot of questions if there are two different Ms in the system. Colormap can always be chosen by the user and this is going to be documented.
