### ISSUE TITLE
"write" method is hidden in tab completion in the Jupyter notebook

### ISSUE THREAD

**Issue by lbreth** [joommf/discretisedfield#34]
When trying to use the "write" method on an object belonging to the Field() class, it doesn't show up in the tab completion in the Jupyter notebook. It does work however, it's just hidden from the user!

Example:

``` 
import discretisedfield as df
system.m = df.Field(mesh, value=m_init, norm=Ms_fun)
system.m.write('skyrmion.vtk') 
```

**Comment by mb1a15** [comment]
I was not able to see this bug. The reason is probably not updated version of `discretisedfield`.
