### ISSUE TITLE
"plot_slice" gives ValueError when vector plane components are zero

### ISSUE THREAD

**Issue by lbreth** [joommf/discretisedfield#35]
Hi, it would be good to plot dots when a the plot_slice method is executed on a discretisedfield object, so to visualize this state as looking at the tip (or the shaft) of an arrow.

Example:

`m = df.Field(mesh, dim=3, value=(1, 0, 0))`
`m.plot_slice("x", L/2)`

gives a ValueError (L is the maximum mesh coordinate).

**Comment by mb1a15** [comment]
This is not how the new plotting method should be called. It should be `m.plot_plane(x=L/2)`. Please look at the plotting documentation at https://github.com/joommf/discretisedfield/blob/master/docs/ipynb/plotting_field.ipynb

**Comment by fangohr** [comment]
Should we maybe raise an error if the old method is used? Or was @lbreth using an older version of the code?

**Comment by lbreth** [comment]
Yes @fangohr , I was using an older version, the one that is still on pip. Marijan will make the new version public this week. I installed it manually, works fine using pip install --editable . from the directory fetched from git directly. I am currently updating the tutorial notebooks to the new version for Durham.
