### ISSUE TITLE
Reading binary files on Windows

### ISSUE THREAD

**Issue by fangohr** [joommf/discretisedfield#45]
We see an error at

https://ci.appveyor.com/project/conda-forge/discretisedfield-feedstock/build/1.0.11/job/pswl16mxt929270y#L505

This probably was always there and we never noticed. First hunch is if we need to open the file explicitly in binary on windows, but didn't dig any further.

The command to run the offending test is `py.test -v discretisedfield/tests/test_field.py -k ovf_file_binary`  (after cloning repo from https://github.com/joommf/discretisedfield).

Could somebody with a windows environment have a look at this?

This currently blocks getting the (updated version of the ) discretisedfield package into conda-forge.

**Comment by marijanbeg** [comment]
This issue is resolved, conda builds.
